import Head from 'next/head';
import { signOut, useSession } from 'next-auth/react';
import { openPopupWindow } from '../helpers';
import Button from '../components/Button';
import { useEffect } from 'react';
import { useRouter } from 'next/router';

export default function Index() {
  const { data: session, status } = useSession();
  const router = useRouter();

  useEffect(() => {
    if (status === 'authenticated') {
      router.push('/account');
    }
  }, [router, status]);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center">
        <h1 className="text-black text-center">
          <span
            className="text-5xl sm:text-5xl lg:text-5xl font-black bg-gradient-to-r from-lime-500 to-green-500 bg-clip-text text-transparent italic px-1">
            OTP Gépkocsinyeremény-betét
          </span>
          <span className="mt-4 block text-5xl sm:text-5xl font-black text-zinc-800">sorsolás értesítő</span>
        </h1>
        <div className="flex flex-row items-center mt-10">
          {session ? <Button label="Kijelentkezés" onClick={() => signOut()} theme="secondary" />
            : <Button label="Bejelentkezés"
                      theme="secondary"
                      onClick={() => openPopupWindow('/google-signin', 'Sample Sign In')} />
          }
        </div>
      </main>
    </>
  );
}