import Head from 'next/head';
import { signIn, signOut, useSession } from 'next-auth/react';
import Button from '../components/Button';
import { useEffect } from 'react';
import { useRouter } from 'next/router';
import Footer from '../components/Footer';

export default function Index() {
  const { data: session, status } = useSession();
  const router = useRouter();

  useEffect(() => {
    if (status === 'authenticated') {
      router.push('/account');
    }
  }, [router, status]);

  return (
    <>
      <Head>
        <title>OTP Gépkocsinyeremény-betét sorsolás értesítő</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-between">
        <div></div>
        <div className="flex flex-col items-center">
          <h1 className="text-black text-center">
            <span
              className="text-3xl sm:text-4xl lg:text-5xl font-black bg-gradient-to-r from-lime-500 to-green-500 bg-clip-text text-transparent italic px-1">
              OTP Gépkocsinyeremény-betét
            </span>
            <span className="mt-4 block text-3xl sm:text-4xl lg:text-5xl font-black text-zinc-800">sorsolás értesítő</span>
          </h1>
          <div className="flex flex-row items-center mt-10">
            {session ? <Button label="Kijelentkezés" onClick={() => signOut()} theme="secondary" />
              : <Button label="Bejelentkezés"
                        theme="secondary"
                        // onClick={() => openPopupWindow('/google-signin', 'Sample Sign In')} />
                        onClick={() => signIn('google')} />
            }
          </div>
        </div>
        <Footer />
      </main>
    </>
  );
}